events {}

http {

    include       mime.types;
    default_type  application/octet-stream;

    server_tokens off;

    sendfile        on;            # high efficiency transporting mode
    tcp_nopush      on;            # reduce network package, improve big file sending
    keepalive_timeout  65;         # keep browser linking, reduce repeating handshake


    upstream wordpress_cluster {
        ip_hash;
        server wordpress1:80;
        server wordpress2:80;


    }

    server {
        listen 80;
        server_name localhost;


        location / {
            proxy_pass http://wordpress_cluster;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

